REM Build Bat File
REM Precheck the Resource 
"C:\Program Files\MRE SDK V3.0.00\tools\ResEditor\CmdShell.exe" save  "D:\MyGitHub\vsm_srv\vsm_srv.vcproj"
REM Copmile c file 
"C:\Program Files\ARM\ADSv1_2\Bin\armcc" -O2 -g -apcs /ropi/rwpi -cpu ARM7EJ-S -o "D:\MyGitHub\vsm_srv\arm\vmmain.o" -c "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\src\vmmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "D:\MyGitHub\vsm_srv\include" -I "D:\MyGitHub\vsm_srv\include\service" -I "D:\MyGitHub\vsm_srv\include\component" -I "D:\MyGitHub\vsm_srv\ResID" -I "D:\MyGitHub\vsm_srv\src\app\widget" -I "D:\MyGitHub\vsm_srv\src\app\launcher" -I "D:\MyGitHub\vsm_srv\src\app\wallpaper" -I "D:\MyGitHub\vsm_srv\src\app\screen_lock" -I "D:\MyGitHub\vsm_srv\include\service" -I "D:\MyGitHub\vsm_srv\include\component" -I "D:\MyGitHub\vsm_srv\include\service" -I "D:\MyGitHub\vsm_srv\src\framework" -I "D:\MyGitHub\vsm_srv\src\framework\ui_core\base" -I "D:\MyGitHub\vsm_srv\src\framework\ui_core\mvc" -I "D:\MyGitHub\vsm_srv\src\framework\ui_core\pme" -I "D:\MyGitHub\vsm_srv\src\framework\mmi_core" -I "D:\MyGitHub\vsm_srv\src\ui_engine\vrt\interface" -I "D:\MyGitHub\vsm_srv\src\component" -I "D:\MyGitHub\vsm_srv\src\ui_engine\framework\xml" -I "D:\MyGitHub\vsm_srv" -errors "D:\MyGitHub\vsm_srv\vsm_srv.log"
REM Copmile c file 
"C:\Program Files\ARM\ADSv1_2\Bin\armcc" -O2 -g -apcs /ropi/rwpi -cpu ARM7EJ-S -o "D:\MyGitHub\vsm_srv\arm\vsm_srv.o" -c "d:\MyGitHub\vsm_srv\vsm_srv.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "D:\MyGitHub\vsm_srv\include" -I "D:\MyGitHub\vsm_srv\include\service" -I "D:\MyGitHub\vsm_srv\include\component" -I "D:\MyGitHub\vsm_srv\ResID" -I "D:\MyGitHub\vsm_srv\src\app\widget" -I "D:\MyGitHub\vsm_srv\src\app\launcher" -I "D:\MyGitHub\vsm_srv\src\app\wallpaper" -I "D:\MyGitHub\vsm_srv\src\app\screen_lock" -I "D:\MyGitHub\vsm_srv\include\service" -I "D:\MyGitHub\vsm_srv\include\component" -I "D:\MyGitHub\vsm_srv\include\service" -I "D:\MyGitHub\vsm_srv\src\framework" -I "D:\MyGitHub\vsm_srv\src\framework\ui_core\base" -I "D:\MyGitHub\vsm_srv\src\framework\ui_core\mvc" -I "D:\MyGitHub\vsm_srv\src\framework\ui_core\pme" -I "D:\MyGitHub\vsm_srv\src\framework\mmi_core" -I "D:\MyGitHub\vsm_srv\src\ui_engine\vrt\interface" -I "D:\MyGitHub\vsm_srv\src\component" -I "D:\MyGitHub\vsm_srv\src\ui_engine\framework\xml" -I "D:\MyGitHub\vsm_srv" -errors "D:\MyGitHub\vsm_srv\vsm_srv.log"
REM Link app 
"C:\Program Files\ARM\ADSv1_2\Bin\armlink" -o "D:\MyGitHub\vsm_srv\vsm_srv.axf"  "D:\MyGitHub\vsm_srv\arm\vmmain.o"  "D:\MyGitHub\vsm_srv\arm\vsm_srv.o" -info totals -rwpi -ropi  "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\percommon.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\pertcp.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\persensor.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\persmsper.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\perbitstream.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\percontact.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\permms.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\persmsmng.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\peraudio.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\percallout.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\percam.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\perfile.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\perhttp.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\persim.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\perrecord.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\persmssp.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\perlbs.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\perpro.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\pervideo.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\perxml.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\persec.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\persysstorage.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\perpayment.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\perbt.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\perpn.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\perudp.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\persysfile.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\persso.a" -errors "D:\MyGitHub\vsm_srv\vsm_srv.log"
REM Pack resource to app 
"C:\Program Files\MRE SDK V3.0.00\tools\ResEditor\CmdShell.exe" pack -silent -resolution 240x320 -o "D:\MyGitHub\vsm_srv\vsm_srv.pkd" -e AXF "D:\MyGitHub\vsm_srv\vsm_srv.vcproj" "D:\MyGitHub\vsm_srv\vsm_srv.axf"
REM Add tag infromation 
"C:\Program Files\MRE SDK V3.0.00\tools\PackDigist.exe" "D:\MyGitHub\vsm_srv\vsm_srv.vcproj" "Vsm_srv" "0.1.0" "RDZDX" "1500" "NotSupportBg" "Not Support rotate" "Vsm_srv" "Vsm_srv" "Vsm_srv" "9246012102087182" "content" " TCP Sensor SMS(person) BitStream Contact MMS SMSMng Audio Call Camera File HTTP SIM card Record SMS(SP) LBS ProMng Video XML Sec SysStorage Payment BT PUSH UDP SysFile sso" "vsm" "ADS" "PKD" "UnCompress" "NoVPI" "Adaptable" "15728960" "UnSysMemAble" "
    " "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  D:\MyGitHub\vsm_srv\arm D:\MyGitHub\vsm_srv\build.log

